### ISSUE TITLE
Cannot add typescript definite assignment assertions to class properties

### ISSUE THREAD

**Issue by lokshunhung** [benjamn/recast#1012]
Recast version: `0.20.5`
Node version: `14.18.2`
Mac OS X version: `12.0.1`

Repro: https://github.com/lokshunhung/recast-definite-repro

[AST explorer](https://astexplorer.net/#/gist/b7ac82659baa9eeb3612616764478269/1551dd3fe807088a8e37298c77643f48fef71987)

---

`recast` with `recast/parser/typescript` can remove [definite assignment assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions) for class properties by setting `ClassProperty.definite = false` (originally `true`)

```ts
// Before
class A {
  foo!: string;
}

// After
class A {
  foo: string;
}
```

but cannot add definite assignment assertions for class properties by setting `ClassProperty.definite = true` (originally `undefined`)

```ts
// Before
class A {
  foo: string;
}

// After
class A {
  foo: string;
}

// should be `foo!: string;`
```

**Comment by eventualbuddha** [comment]
It looks like recast doesn't know about that property: https://github.com/benjamn/recast/blob/4b1fc1678fb4d3009be354721366496462d1c85c/lib/printer.ts#L1452

Should be pretty easy to fix. Want to submit a PR?

**Comment by lokshunhung** [comment]
@eventualbuddha Sure, #1013
