### ISSUE TITLE
Add swc parser

### ISSUE THREAD

**Issue by GianlucaGuarini** [benjamn/recast#1014]
What do you think about adding the [swc](https://swc.rs/docs/usage/core) parser? 

```js
import { parseSync } from '@swc/core'
import {parse} from 'recast'

/**
 * Parse a js source to generate the AST
 * @param   {string} source - javascript source
 * @param   {Object} options - parser options
 * @returns {AST} AST tree
 */
export default function generateAST(source, options) {
  return parse(source, {
    parser: {
      parse: parseSync
    },
    ...options
  })
}
```

I am trying handling this feature outside of recast but it seems that the parser output is not yet compatible

**Comment by GianlucaGuarini** [comment]
Notice that this topic was already discussed on the swc repo https://github.com/swc-project/swc/issues/1392

**Comment by benjamn** [comment]
@GianlucaGuarini This seems like a good idea! If you have time to get things started (using the other parsers as a guide), I would be happy to look at a PR.

**Comment by GianlucaGuarini** [comment]
@benjamn it seems that the swc author is [rewriting it in golang](https://kdy1.dev/posts/2022/1/tsc-go) and probably it makes more sense to wait a bit before starting working on this patch.

**Comment by reesericci** [comment]
STC has been abandoned: https://github.com/dudykr/stc/issues/1101

**Comment by GianlucaGuarini** [comment]
Fair enough we can close this issue

**Comment by reesericci** [comment]
I don't think it needs to be closed, SWC still has a parser, we just can work on implementing it now instead of waiting on STC

**Comment by GianlucaGuarini** [comment]
No progress towards this issue was done during the last 2 years. I think it makes sense to close it anyway as it become stale
