### ISSUE TITLE
Quotes are broken in recast v0.21.0

### ISSUE THREAD

**Issue by coderaiser** [benjamn/recast#1023]
After updating I see that:

```js
const { parse, print} = require("recast");
const {StringLiteral, ExpressionStatement}= require('@babel/types');

const ast = parse(`const a = 5`, {
    parser: require("recast/parsers/babel")
});

ast.program.body.unshift(ExpressionStatement(StringLiteral('strict mode')));

console.log(print(ast, {
    quote: 'single',
}));
```

Produces

```js
PrintResult { code: '"strict mode";\nconst a = 5' }
```

And `quote` option is ignored.

`recast v0.20.0` produces:

```js
PrintResult { code: "'strict mode';\nconst a = 5" }
```

The problem begins from this commit: https://github.com/benjamn/recast/commit/8e542935d0fd1e7265e00c4946514aa9d181e114

**Comment by cos** [comment]
Another 👍 for the fix to be merged. Also blocking us from to updating to `0.21`

**Comment by coderaiser** [comment]
You can use a fork where it's fixed [`@putout/recast`](https://github.com/putoutjs/recast).
