### ISSUE TITLE
Adding a property to an object

### ISSUE THREAD

**Issue by ndr47** [benjamn/recast#1040]
I want to modify properties to a particular typescript object.

This is the file content:
```typescript
// /path/to/my/file.ts
...
import somelib from 'somelib';
...
export const theobj:MyType = {
  thekey: {
    prop1: 5,
    prop2: 6
  }
} 
...
```

I want to remove `prop1` and add a `prop3` to prop `thekey` inside the object `theobj`.

This is my code:
```typescript
import fs from 'fs';
import * as recast from 'recast';

const source = fs.readFileSync('/path/to/my/file.ts', 'utf-8');

const ts_ast = recast.parse(source, {
	 parser: require("recast/parsers/typescript")
});

const all = ts_ast.program.body;

for(const node of all){
	if(node.type === recast.types.namedTypes.ExportNamedDeclaration.toString()){
		const variable_declaration = node.declaration;
		const variable_declarator = variable_declaration.declarations[0];
		if(variable_declarator.id.name === 'theobj'){
			for(const prop_def of variable_declarator.init.properties){
				if(prop_def.key.name === 'theykey'){
					for(let i = 0; i < prop_def.value.properties.length; i++){
				  		const prop_obj = prop_def.value.properties[i];
						if(prop_def.key.name === 'prop1'){
							delete prop_def.value.properties[i];
						}
					}
					
					const id = recast.types.builders.identifier('prop3');
					const value = recast.types.builders.stringLiteral("'a str value'");
					const obj_prop = recast.types.builders.objectProperty(id, value);

					prop_def.value.properties[0].insertAfter(obj_prop);
					break;
				}
			}
			break;
		}
	}
}

const printed = recast.print(ts_ast).code;
console.log(printed);

```

Even though the `delete` works perfectly, the `insertAfter` does not.

I get:
```
insertAfter is not a function
```

I've checked and I saw that `prop_def` is a `Node` and not a `NodePath`. It is `NodePath` that has the method `insertAfter`.

In the [`README`](https://github.com/benjamn/recast#readme) it says: *"Now do whatever you want to ast. Really, anything at all!"*, but it doesn't say what are the methods to add a new `Node`.

**Comment by eventualbuddha** [comment]
The property list is just a standard `Array`, not a `NodeList` or some other DOM object. Just use `push` or `splice` or `unshift` as appropriate.

**Comment by ndr47** [comment]
Thanks for the answer. However it doesn't work. I am still getting:

```
prop_def.value.properties[0].push(obj_prop);
TypeError: prop_def.value.properties[0].push is not a function
```
Plus I don't think this is the proper way. 

Is there any documentation or examples on how to add a property to an object? I believe it should be a common operation.

**Comment by eventualbuddha** [comment]
You want this:

```js
prop_def.value.properties.push(obj_prop);
```

The `properties` value is an `Array`. Please check the `Array` documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array.
