### ISSUE TITLE
Error: did not recognize object of type "TSInstantiationExpression"

### ISSUE THREAD

**Issue by Arooba-git** [benjamn/recast#1230]
Hi 👋 
I'm using recast with babel parser, and getting this error when trying to parse any file containing TSInstantiationExpression. Is recast missing TSInstantiationExpression support or am I missing something? 🤔

<img width="950" alt="Screen Shot 2022-11-22 at 6 15 55 AM" src="https://user-images.githubusercontent.com/56495631/203684651-c09e566f-f1bb-429e-a72b-2d8725df4623.png">

**Comment by Arooba-git** [comment]
bump

**Comment by iliakan** [comment]
Is there any workaround or a temporary fix for that? I'd be happy just to ignore this, just not to die.

My jscodeshift auto-refactoring script fails to work on real-life files because of that. Even though it doesn't need to refactor any TSInstantiationExpressions.

**Comment by eventualbuddha** [comment]
Does it fail on _every_ file? Or only files with `TSInstantiationExpression`s? You could comment them out for now.

**Comment by iliakan** [comment]
I have a large codebase, 100+ files have `TSInstantiationExpressions`s. The refactoring script fails on them.

**Comment by iliakan** [comment]
Without any type of pressure, may I kindly wonder, is this going to be fixed soon?

I saw a commit has landed, but not sure how much work is ahead.

Thank you for what you do!

**Comment by benjamn** [comment]
The remaining work in https://github.com/benjamn/recast/pull/1232 is worthwhile for completeness but not necessarily relevant unless you're using `ClassAccessorProperty` (a very new AST node type).

@iliakan If you want to test the current changes locally, you should be able to run this command to install `recast@0.23.0-pr1232.0`:
```sh
npm i recast@pr-1232
```
If this is useful, let me know. I might try to automate it for any PR, so it's easier for folks to test/use any proposed changes.

**Comment by iliakan** [comment]
Last time it worked without errors (but I did not check the outcome). I'll retest again after I rewrite some stuff ;)

**Comment by benjamn** [comment]
Alright folks, please try running `npm i recast@next` to get version 0.23.1, which includes support for `TSInstantiationExpression` and some other AST types that were lagging behind Babel.

Since I have not tagged this version as `latest` on npm yet, we can still fix bugs relatively easily, if you encounter anything strange after updating.
