### ISSUE TITLE
Consider removing usage of Node.js builtins

### ISSUE THREAD

**Issue by d3lm** [benjamn/recast#1235]
I'd like to use this library in the browser and noticed it uses `assert`, and `os` from Node.js, only for `os.EOL` and some assertion functions like `ok`. While Webpack 4 polyfills Node.js builtins automatically, it's not ideal, as those polyfills often cause issues. For that reason, Webpack 5 no longer polyfills these modules. This is also the case for Vite.

I was wondering if we could remove these and use alternatives or require them but fallback to some alternatives so this package would work in the browser as well as with Node.js.

**Comment by eventualbuddha** [comment]
I'd be interested in seeing this too, but I don't have time to do it myself. I can review a PR, though.

**Comment by d3lm** [comment]
I'll submit a PR 🙏

**Comment by d3lm** [comment]
Here you go https://github.com/benjamn/recast/pull/1237. Let me know if you want me to change something.
