### ISSUE TITLE
Implement printer cases for TypeAnnotation-related AST nodes

### ISSUE THREAD

**Issue by benjamn** [benjamn/recast#132]
See the `TODO`s here: https://github.com/benjamn/recast/blob/5071a80ac09524fbd124a4c99eaf44746f32d941/lib/printer.js#L973-L1006

cc @jeffmo @gabelevi @amasad

**Comment by demoneaux** [comment]
I think this issue can be closed as [type annotations are already implemented](https://github.com/benjamn/recast/blob/9b32ded58db4538b644d59a156a0a95959b147a1/lib/printer.js#L1214-L1444).

**Comment by benjamn** [comment]
Quite right @bnjmnt4n!
