### ISSUE TITLE
TSX support

### ISSUE THREAD

**Issue by sergeyzwezdin** [benjamn/recast#1382]
Trying to parse React (tsx) code, but `recast` fails with error.

```tsx
import * as recast from 'recast';

recast.parse(`import {FC} from 'react';
    
export const Button: FC = () => {
    return <div>button</div>;
}`, {
    parser: require('recast/parsers/typescript')
})
```

> Unterminated regular expression. (4:24)
> SyntaxError: Unterminated regular expression. (4:24)
>    at constructor (/node_modules/@babel/parser/src/parse-error.ts:81:19)
>    at V8IntrinsicMixin.toParseError [as raise] 

Does `recast` support React/TSX code parsing?

**Comment by eventualbuddha** [comment]
Try the `babel-ts` parser instead?

```ts
import * as recast from "recast";
import * as ts from "recast/parsers/babel-ts";

console.log(
  recast.parse(
    `import {FC} from 'react';

export const Button: FC = () => {
    return <div>button</div>;
}`,
    {
      parser: ts,
    },
  ),
);
```
