### ISSUE TITLE
Pretty print option for no semicolons?

### ISSUE THREAD

**Issue by jprichardson** [benjamn/recast#140]
Since semicolon-less JavaScript is gaining in popularity, would you be willing to add an option to the pretty printer to forgo them?

**Comment by caridy** [comment]
:no_entry_sign:

**Comment by benjamn** [comment]
There are a lot of somewhat arbitrary stylistic choices embedded in the printer code, and I'm not sure I want to go down the rabbit-hole of making some/all of them configurable.

I'm happy to look at pull requests, but please note that printing without semicolons is not as simple as omitting semicolons after statements. You'll have to respect the subtleties of [Automatic Semicolon Insertion](http://stackoverflow.com/questions/2846283/what-are-the-rules-for-javascripts-automatic-semicolon-insertion-asi), and you might even have to add initial semicolons to lines that start with `(` or '['.

In the meantime, I would suggest using [this standalone tool](https://github.com/yyx990803/semi) to insert or strip semicolons from your code.
