### ISSUE TITLE
thanks for all the work :)

### ISSUE THREAD

**Issue by jeromeetienne** [benjamn/recast#150]
Hi

Not really an issue, Just a word to thanks you for the library and to let you know how useful your library has been. i used it to parse and rewrite the javascript to do 'jsdoced javascript' http://jsdoced.org it is a js-to-js compiler which parses jsdoc to implement strong typing and private visibility to javascript.

Thanks again

**Comment by benjamn** [comment]
@jeromeetienne Thanks for the kind words! Your success using Recast is exactly what makes this project rewarding for me.

**Comment by jeromeetienne** [comment]
my pleasure. btw i meant http://jsdocedjs.org

**Comment by briandipalma** [comment]
+ 100
