### ISSUE TITLE
Why are comment nodes not `configurable`?

### ISSUE THREAD

**Issue by briandipalma** [benjamn/recast#151]
As part of the code converter I'm building we'd like our comments to appear in different places in the finished AST. For example:

```javascript
// Some doc.
my.namespace.Class = (function() {

function Class() {}

return Class;
});
```

Should be converted to

```javascript
// Some doc.
function Class() {}

module.exports = return Class;
```

This is easy enough in theory, I take the `Program` comment and attach it to the constructor function declaration node and remove it from the `Program` node. Sadly comments are not `configurable` so I can't define them to be `undefined` so the Program comment is printed twice.

I was wondering if there was a reason for this choice or was it just a case of using the default behaviour of `defineProperty`.

**Comment by briandipalma** [comment]
PR if this can be changed https://github.com/benjamn/recast/pull/152

**Comment by benjamn** [comment]
Quick update: the `.comment` property is now a simple (enumerable, writable, configurable) object property, created without using `Object.defineProperty` at all: https://github.com/benjamn/recast/commit/b35be9aa74ad4c51234054bf4d1cbc904f9a9534

**Comment by briandipalma** [comment]
OK, is this new release meant to address the double comment bug? Is there are new feature (reved the minor number I noticed)? Thanks!

**Comment by briandipalma** [comment]
Issues fixed, excellent thank you very much!
