### ISSUE TITLE
Treat comment objects as reprintable AST nodes

### ISSUE THREAD

**Issue by benjamn** [benjamn/recast#153]
Modifying the text of a comment currently does not guarantee that the comment will be reprinted with the new text, for a couple of different reasons:
  * Comments are treated a lot like whitespace, so old comments often just reappear in the output with no consideration for whether they have been altered.
  * [The `Patcher` code](https://github.com/benjamn/recast/blob/master/lib/patcher.js) doesn't make any attempt to substitute new comments for old comments.

At the very least, we need to store comments on the `.original` AST nodes and copy them in [`TreeCopier#copy`](https://github.com/benjamn/recast/blob/053630a744253949ce2609be9e158f76065e07ce/lib/parser.js#L63), so that we can actually begin to detect changes.

**Comment by jugglinmike** [comment]
Working beautifully; thanks!
