### ISSUE TITLE
what is the status of recast about es6 ?

### ISSUE THREAD

**Issue by jeromeetienne** [benjamn/recast#154]
Hi

es6 is coming. so i was wondering, what was the status of recast about es6 ? is it currently supported ? is there a plan for it ? is it supposed to happen in a dependant library e.g. esprima. ? you see this kind of thing...

no pressure, it is just that i was wondering and i looked at the readme and found no mentions about it :)

Jerome

**Comment by benjamn** [comment]
Recast depends on https://www.npmjs.com/package/esprima-fb by default, which has support for many ES6 features. Note that you can use a different version of Esprima, or even a totally different parser, by passing it to `recast.parse(source, { esprima: objectWithParseMethod })`. The parser must have a similar interface to Esprima, but I know that https://github.com/marijnh/acorn works pretty well, for example.

The `recast.visit` utility supports everything defined in https://github.com/benjamn/ast-types/blob/master/def/es6.js, and even some proposed ES7 features: https://github.com/benjamn/ast-types/blob/master/def/es7.js, so you should have no trouble writing visitors with methods like `visitComprehensionExpression` or `visitTemplateLiteral`. While I recommend using `recast.visit`, you can use whatever transformation strategy works best for you—`recast.parse` and `recast.print` are designed to assume as little as possible about the transform process. Another popular transformation utility is https://github.com/estools/estraverse.

In other words, parsing and printing should be fully ES6-ready. But what about recast.print?

The answer depends on your needs: in https://github.com/benjamn/recast/blob/master/lib/printer.js you can see a complete list of AST nodes that Recast knows how to pretty-print, and https://github.com/benjamn/recast/blob/master/test/syntax.js guarantees that every AST type in `recast.types.namedTypes` has a `case` statement in that big `switch` statement. Towards the bottom of the file, you'll find some `// TODO` comments for node types that have not yet been implemented. If you have a specific need for one of those, I'm happy to give it special attention—just file an issue!

In general, `recast.print` will just copy the original code for AST nodes that were not modified, and that copying does not require the printer to know how to print the node. So in a lot of cases you may not actually need a fully-implemented printer case for a particular node type, unless you're specifically transforming nodes of that type. On the other hand, if you're using `recast.prettyPrint`, then every node in the AST will need a printer case. However, if you're writing a transpiler from ES6 to ES5, and it replaces all the nodes of a type unknown to the printer with ES5-type nodes, then you have nothing to worry about.

Thanks for the question. I hope this answer helps, and I agree that it probably deserves a spot in README.md.

**Comment by rwaldron** [comment]
I just came here to file a bug and saw this, but now I'm not sure where to file the bug, so consider this a request for guidance. Take a look at the following: 

Source:
```js
class Base {
  m() {
    return ' base m';
  }
}
class Derived extends Base {
  ['a']() { return 'a' + super.m(); }
  [ID('b')]() { return 'b' + super.m(); }
  [0]() { return '0' + super.m(); }
  [ID(1)]() { return '1' + super.m(); }
}
```

Result: 

```js
class Base {
  m() {
    return " base m";
  }
}
class Derived extends Base {
  "a"() { return "a" + super.m(); }
  ID("b")() { return "b" + super.m(); }
  0() { return "0" + super.m(); }
  ID(1)() { return "1" + super.m(); }
}
```

**Comment by jeromeetienne** [comment]
Thanks a lot for the extensive explaination! 

i will use ```recast.print``` as you advice, and ```visitArrowFunctionExpression``` to intercept the arrow function.
