### ISSUE TITLE
Computed Properties losing brackets when printed

### ISSUE THREAD

**Issue by rwaldron** [benjamn/recast#156]
See: https://github.com/benjamn/recast/issues/154#issuecomment-74956625

**Comment by rwaldron** [comment]
Just wondering if there was anything I could do to help with this? We're using recast in our tooling as we migrate V8 tests to test262 and this particular issue is blocking progress on computed property tests—the alternative is to re-write every test by hand :(

**Comment by benjamn** [comment]
Published a fix to NPM as v0.10.2: npmjs.org/package/recast
