### ISSUE TITLE
Prominently link to `ast-types` readme in the documentation.

### ISSUE THREAD

**Issue by jamestalmage** [benjamn/recast#157]
Lot's of really helpful info there.

**Comment by benjamn** [comment]
Great idea, especially for `recast.visit`, which is identical to `require("ast-types").visit`.

**Comment by jamestalmage** [comment]
I certainly wish I'd known about it two hours ago! :smirk:

**Comment by benjamn** [comment]
Fixed by 6a38dba104915b5bc3627ace69836c94778b81ff, thanks!
