### ISSUE TITLE
Allow fine grained control over how and where nodes are printed.

### ISSUE THREAD

**Issue by jamestalmage** [benjamn/recast#160]
In my specific use case, this:

```javascript
// mocha-test.js
/* @customAnnotation */
var a;
```
becomes this:
```javascript
// mocha-test.js
/* customAnnotation consumed */
var a;

beforeEach( function () {
  /* boilerplate initializing var a; */
});
```

It all works great (thank you!), but source-maps pose a bit of a problem. 
If mine is the only transform in the tool chain, recasts source-map support makes it easy, but upstream/downstream transforms add to the complexity. Some tools (i.e. gulp) make it easy, others (i.e. browserify) make it hard to impossible. Not to mention potential bad actors up/downstream.

If I was able to manipulate the resulting output to be:
```javascript
// mocha-test.js
/* customAnnotation consumed */
var a; beforeEach( function () {/* boilerplate initializing var a; */ });
```
Then my transform essentially has zero impact on the source map, and I can worry about other things.

I'm guessing it is a matter of visiting every generated node and setting `loc` correctly, but that seems... not trivial?

**Comment by benjamn** [comment]
Do you care if the `beforeEach(...)` expression is reflected in the source map? If not, then we could have an alternate pretty-printer mode that tries to print certain nodes all on one line. Not sure how tricky that would be, but it seems doable.

Tangentially, I'd love to improve the API for working with source maps so that it would be easier to work with other tools (see #109, #115, #128, #146).

It would also be great if pretty-printing supported source maps (right now only `recast.print` will give you a source map).

**Comment by jamestalmage** [comment]
> Do you care if the beforeEach(...) expression is reflected in the source map? 
No it is for the specific case where the sourcemaps I output are getting overwritten by downstream transforms. 

It would be nice to do both (output a correct sourcemap in the hopes it is consumed correctly by downstream transforms, while guarding against the possibility that it won't be). If my short term options are one or the other, I can always make that decision per plugin (i.e sourcemaps for my gulp plugin, a one-liner for browserify), and provide config flags.

**Comment by jamestalmage** [comment]
> Tangentially, I'd love to improve the API for working with source maps so that it would be easier to work with other tools (see #109, #115, #128, #146).

Yep, saw those (and am borrowing liberally from #115, and #146 in my own code until a final solution lands here).

**Comment by jamestalmage** [comment]
closing this. I got source-maps working working. I'm not sure what I was doing wrong that it was working in gulp and not browserify.
