### ISSUE TITLE
ast-types accessed via require doesn't have type `File` defined.

### ISSUE THREAD

**Issue by jamestalmage** [benjamn/recast#165]
I started getting an error in new commits saying `File` was an unknown type.

The fix was pretty easy: https://github.com/jamestalmage/angular-test-utils/commit/1cb82464ed40f11d557fba65304117fbbd09eec0

Not sure if this is an issue you need to know about, or if I was just doing it wrong before.
Feel free to close if it's the latter.

**Comment by fkling** [comment]
ast-types was bumped to 0.7 a couple of hours ago: https://github.com/benjamn/ast-types/commit/3eb728aee421ea5888c033e20dbdce5213f7b993. So yeah, the issue is likely that you installed the latest recast, but not the latest ast-types.

**Comment by benjamn** [comment]
Yeah, as long as you're using `require("recast").types` everywhere instead of using `require("ast-types")` directly, you can't go wrong.

**Comment by jamestalmage** [comment]
Sweet. Figured it was that!
