### ISSUE TITLE
Exchanging string literals against identifiers can lead to invalid code

### ISSUE THREAD

**Issue by davidaurelio** [benjamn/recast#170]
When parsing `return "a string"` with recast, and swapping the `'Literal'` node in the AST with an identifier (like `{ type: 'Identifier', name: 'arbitrary' }`), `recast.print` will produce invalid code: `returnarbitrary`;

Minimal example:

```js
var recast = require('recast');
var ast = recast.parse('return"a string"');
ast.program.body[0].argument = { type: 'Identifier', name: 'arbitrary' };
recast.print(ast).code; // returnarbitrary
```

**Comment by benjamn** [comment]
Thanks for catching this, and sorry it's causing you problems!

For the sake of completeness (so nothing like this ever happens again), I'm wondering if this kind of problem can ever arise in a situation where the identifier or keyword comes after the replaced expression. Something like `"string"foo` becoming `nullfoo`, if that syntax could ever appear legally in the language… any concerns there?

**Comment by benjamn** [comment]
I think I've fixed this in the most generic way I could: 96f2320052e4be700b75eba07ba6035c7872cca6 (it also affects `throw`, `yield`, and `await` keywords, at the very least).

**Comment by davidaurelio** [comment]
Thanks for fixing this so quickly, I will try it out tomorrow.
And no need to excuse, nobody thinks of all cases in advance. Keep up the good work!

**Comment by davidaurelio** [comment]
There are other operators, but those should already be catched by your fix (`typeof`, `void`).

Binary keyword operators that can have a string on the left hand side are `in` and `instanceof` (although it probably won’t happen for the latter).

**Comment by benjamn** [comment]
Ah ha! So I'm pretty sure the same problem will happen if you parse `"foo"in bar` and replace `"foo"` with `x`, which convinces me `needsTrailingSpace` is also necessary.
