### ISSUE TITLE
can't parse multi-line comments in jsx expressions

### ISSUE THREAD

**Issue by jenseng** [benjamn/recast#175]
occasionally i'll put a [multi-line comment](https://facebook.github.io/react/docs/jsx-in-depth.html#comments) inside an otherwise empty jsx expression, e.g.

```js
    return (
      <div className="authoring-heading white padding-t-s padding-l-m">
        {/* this will kick back to a react route, but it's in a different
            react-outlet, so we have to do the ember dance */}
        <EmberLink
          to={["react.author.survey", this.props.survey.id]}
          className="right large padding-r-m"
        >
          <ScreenReaderContent children={I18n.t("Close")} />
          <Icon className="gs-x gs-half white" />
        </EmberLink>
        ...
      </div>
    );
```

but then i can't use recast, because it blows up with:

```
/path/to/node_modules/recast/lib/comments.js:108
        throw new Error("Comment location overlaps with node location");
              ^
Error: Comment location overlaps with node location
    at decorateComment (/path/to/node_modules/recast/lib/comments.js:108:15)
    at decorateComment (/path/to/node_modules/recast/lib/comments.js:84:13)
    at decorateComment (/path/to/node_modules/recast/lib/comments.js:84:13)
    at decorateComment (/path/to/node_modules/recast/lib/comments.js:84:13)
    at /path/to/node_modules/recast/lib/comments.js:129:9
    at Array.forEach (native)
    at exports.attach (/path/to/node_modules/recast/lib/comments.js:127:14)
    at Object.parse (/path/to/node_modules/recast/lib/parser.js:54:5)
    at [eval]:1:47
    at Object.<anonymous> ([eval]-wrapper:6:22)
```

it appears that it's the multi-line-ness of the comment that causes the problem, i.e. this blows up:

```js
recast.parse('<b>{/*\n     * TODO need copy\n     */}</b>')"
```

but this doesn't:

```js
recast.parse('<b>{/* TODO need copy */}</b>')"
```

**Comment by jenseng** [comment]
I haven't really investigated, but perhaps removing that `throw` would fix it? Or would we then miss out on legitimate problems? Could just be the logic needs a little tweaking

**Comment by benjamn** [comment]
I haven't investigated yet, either, but I suspect the parsing logic for comments in JSX produces bad `.loc` information. The problem is definitely real: the `.loc.start` of the node comes before the `.loc.start` of the comment, but the `.loc.end` of the comment falls after the `.loc.end` of the node.

**Comment by jenseng** [comment]
Yeah, it's an issue with esprima-fb ... The `.loc` information on the `JSXEmptyExpression` is where it's messed up; it "ends" on line 1, with a too-big column number ... it's counting the newlines as not-newlines, so it just thinks it's all a single line (whereas the `Block`, the `JSXExpressionContainer` and its ancestors all have the expected `.loc.end`)

I'll see if I can get it fixed upstream. At any rate, I noticed there weren't really an JSX tests here, so I'll submit a PR w/ a bunch (including a skipped failing test for this).

**Comment by jenseng** [comment]
If it ends up being too hairy to fix it in esprima-fb, perhaps `decorateComment ` could be special-cased to ignore `JSXEmptyExpression`'s incorrect `.loc`? Though that could have repercussions later when transforming/printing ¯\_(ツ)_/¯

**Comment by benjamn** [comment]
There's precedent for setting `.loc = null` when a node's `.loc` is unusable for any reason: https://github.com/benjamn/recast/blob/613daa84df8e118ebd8b04eec8bdf1cd7246896e/lib/util.js#L124

That would have the side-effect of preventing comments from being attached to the node, which might help with this problem, though it seems like the `JSXEmptyExpression` is the right node to attach the comments to, in this case, so maybe that's a poor solution.

**Comment by jenseng** [comment]
Yeah, I think [this fix to esprima-fb](https://github.com/facebook/esprima/pull/108) is the way to go. Assuming it's accepted, we could just close out this ticket.

**Comment by jenseng** [comment]
esprima-fb PR has been merged, we should be good to go on the next version

**Comment by benjamn** [comment]
Yay \o/
