### ISSUE TITLE
Extra lines in re-attached comments

### ISSUE THREAD

**Issue by zertosh** [benjamn/recast#181]
I'm trying to break up a single `var` with multiple declarations into individual `var`s - while preserving the comments. I'm getting new lines introduced where I didn't expect them - any ideas why?

```js
var recast = require('recast');
var b = recast.types.builders;

var ast = recast.parse([
  '// comment 1',
  'var a = 1,',
  '    // comment 2',
  '    b = 2;'
].join('\n'));

recast.visit(ast, {
  visitVariableDeclaration: function(path) {
    var newDecls = path.node.declarations.map(function(decl) {
      var newDecl = b.variableDeclaration('var', [decl]);
      // re-attach comments
      newDecl.comments = decl.comments;
      decl.comments = null;
      return newDecl;
    });
    newDecls[0].comments = path.node.comments;
    path.replace.apply(path, newDecls);
    this.traverse(path);
  }
});

console.log(recast.print(ast).code);
```

That will output:

```js
// comment 1
var a = 1;

// comment 2
var b = 2;
```

When I expected:

```js
// comment 1
var a = 1;
// comment 2
var b = 2;
```

Removing "comment 1" or "comment 2" from the source still introduces a new line between `a` and `b`.

**Comment by benjamn** [comment]
Ah, yes, the pretty-printer tries to make sure there's a blank line around any multi-line statement, and these two variable declarations become "multi-line" when you add a comment to either one of them. I suspect if you removed both comments, the `var`s would collapse together.

It might be possible to determine if a statement is multi-line without looking at the comments, but I'm not totally convinced that's best. Happy to consider it, though.

If you're just wondering if this behavior is expected, the answer is definitely yes!

**Comment by zertosh** [comment]
>  I suspect if you removed both comments, the vars would collapse together.

Yup, they collapse.

> It might be possible to determine if a statement is multi-line without looking at the comments, but I'm not totally convinced that's best. Happy to consider it, though.

It's a bit annoying, but now the reason for it makes sense. The code I'm trying to re-style is very uniform, so I can handle those extra blank lines in a post-processing step.

Thanks for the quick response!
