### ISSUE TITLE
Is there any option to force line break explicitly?

### ISSUE THREAD

**Issue by grabbou** [benjamn/recast#182]
Say I have two nodes already separated 

```
var a = 5;

var b = 5;
```
I'd like to have
```
var a = 5;

var b = 5;

var c = 6;
```
instead of
```
var a = 5;

var b = 5;
var c = 6;
```
when doing `node.get('children').push(newNode)`.

Any ideas? Note, the real-life example is more complex (the elements are function declarations), but wanted to keep the sample code slick.

**Comment by grabbou** [comment]
`node.get('children').push('\n', newNode).` does the trick!

**Comment by benjamn** [comment]
Oh wow, I hadn't even considered that, but it should work!

**Comment by grabbou** [comment]
So far I've managed it to work in this case -> https://github.com/grabbou/este-cli/blob/master/blueprints/route/index.js#L124 :)
Do you consider implementing such a feature in a less hacky way? Can help you out with a PR.
