### ISSUE TITLE
How to ensure that newly injected statements respect indentation rules of the rest of the file?

### ISSUE THREAD

**Issue by platinumazure** [benjamn/recast#184]
What's the best way to ensure that newly created statement nodes respect the indentation rules of the rest of the file?

Presumably variations can result due to the lack of line context information in the newly created node (i.e., line and column offsets). But is there an easy way to get the printer to "infer" what's correct based on the next or previous lines' information?

Might be similar to #129.

**Comment by benjamn** [comment]
The printer already infers `options.tabWidth` if you don't specify it explicitly: https://github.com/benjamn/recast/blob/24ebc0e110aed78326fc1278d888912c4a53cb7b/lib/printer.js#L74

If you mean something more sophisticated than tab width, like how deeply multi-line function parameter lists are indented, I'm afraid there's a very long tail of different scenarios to deal with, and I'm not even sure the "rules" can be written down in a coherent way. Feel free to elaborate on what you have in mind, though!

**Comment by platinumazure** [comment]
Tab width is fine (and to recast's credit, the indentation level in terms of spaces is exactly where it should be), but it uses spaces for new statements even if the rest of the file uses tabs for indentation.

I'm on my mobile right now, but when I get to a PC I can show a test case.

**Comment by platinumazure** [comment]
And I should add I'm aware of `{ useTabs: true }`, but it would be nice if recast could sort of... infer it? I'm processing many files in multiple directories and unfortunately I'm dealing with some inconsistency in style, so... For my use case, preserving the existing code style per file is more important (for now) than complete uniformity.

Does that make sense?

**Comment by benjamn** [comment]
Oh! Inferring `options.useTabs` seems totally doable. Want to open an issue when you get back to your computer?

By the way, when the indentation (as measured in spaces) hasn't changed, the original white space (possibly including tabs) will often be reused, even if the code on that line has changed. But you're right about totally new (or reindented) lines of code.

**Comment by benjamn** [comment]
(Sorry, by "open an issue" I guess I meant updating the title of this issue.)

**Comment by platinumazure** [comment]
Nah, it's okay, I'll close this one and open another one that's more technical/low-level.
