### ISSUE TITLE
Support for ES7 Property Initializers

### ISSUE THREAD

**Issue by joshblack** [benjamn/recast#188]
Was trying to use `recast` on a react project and ran into an issue with it not being able to parse `static` property initializers. For example:

```
class App extends Component {
  static defaultProps = { /* ... */ };
}
```

Which results in an unexpected token error. Since these are ES7+ I understand why I shouldn't expect this to work, but is there any way for `recast` to parse these initializers and, if not, is there any way that I can add them to `ast-types` to allow me to visit these properties when going through the AST? Thanks!

**Comment by benjamn** [comment]
Why the close? This seems like a legitimate issue!

The usual strategy for adding a new syntax feature is to add a type definition to https://github.com/benjamn/ast-types/blob/master/def/es7.js and then add a pretty-printer case to https://github.com/benjamn/recast/blob/master/lib/printer.js.

**Comment by joshblack** [comment]
Ended up thinking it wasn't an appropriate issue for some reason. Thank you so much for taking the time to respond! I'll definitely look into adding the type definition and pretty-printer case.
