### ISSUE TITLE
There is no 0.10.18 release.

### ISSUE THREAD

**Issue by jameswlane** [benjamn/recast#195]
`package.json` and npm has recast at v`0.10.18` yet there isn't a release that version to its failing to install.

**Comment by benjamn** [comment]
[Done](https://github.com/benjamn/recast/releases/tag/v0.10.18), though can I ask in what context/toolchain/workflow the package was failing to install? I haven't been all that diligent about pushing release tags until recently, so I wonder how it was working for you before…

**Comment by jameswlane** [comment]
I was installing `gulp-jsx-coverage` it looks like one of it's dependencies -> dependancies
