### ISSUE TITLE
Template string backticks are being stripped during prettyPrint

### ISSUE THREAD

**Issue by nickjvm** [benjamn/recast#210]
See gist: https://gist.github.com/nickjvm/9ce1823f3ef6574952a9

**Comment by benjamn** [comment]
Um yeah that's a problem. Fixing immediately!

**Comment by benjamn** [comment]
Fixed in [0.10.30](https://github.com/benjamn/recast/releases/tag/v0.10.30).

**Comment by nickjvm** [comment]
Awesome, thanks for the quick turnaround!
