### ISSUE TITLE
Missing parenthesis on async arrow function where the first argument is an array destructuring

### ISSUE THREAD

**Issue by vjeux** [benjamn/recast#217]
Input:

```javascript
([a, b]) => {}
```

codemod (just puts `async = true`)

```javascript
module.exports = function(file, api) {
  const j = api.jscodeshift;
  const {expression, statement, statements} = j.template;

  return j(file.source)
    .find(j.ArrowFunctionExpression)
  	.forEach(p => p.value.async = true)
    .toSource();
};
```

result:

```javascript
async [a, b] => {}
```

but this doesn't parse. Should be

```javascript
async ([a, b]) => {}
```

<img width="1374" alt="screen shot 2015-10-18 at 8 17 57 pm" src="https://cloud.githubusercontent.com/assets/197597/10569068/a3d310fa-75d5-11e5-9895-0f244e67482f.png">

**Comment by vjeux** [comment]
cc @cpojer

**Comment by cpojer** [comment]
This should be easy to fix but I'm wondering what the status of async arrow functions in ES2016 is – last I heard they are going to be removed from Babel 6 and are not going to be part of the spec.

**Comment by cpojer** [comment]
I guess this basically means that if the first argument is neither array or object destructuring (ie. it is an identifier) we have to wrap in parenthesis. PR incoming.
