### ISSUE TITLE
Remove trailing semicolon from ObjectExpression in static ClassProperty

### ISSUE THREAD

**Issue by joshblack** [benjamn/recast#237]
Initial issue: facebook/jscodeshift#74

Was looking into how to add a ClassProperty inside of a ClassDeclaration, specifically a static one containing an ObjectExpression. For this, my builder looks similar to the following in jscodeshift:

```js
.replaceWith(
  (p) => j.classBody([
           j.classProperty(
             j.identifier('propTypes'), 
             j.objectExpression(propTypes), 
             null, 
             true
           ),
           ...p.node.body
         ]));
```

However, a trailing semicolon is added in the transformation, so instead of:

```js
class Foo {
  static foo = {
    bar: 'baz'
  }
}
```

The transformation looks like:

```js
class Foo {
  static foo = {
    bar: 'baz'
  };
}
```

Is there any way to exclude this semicolon after the class property definition? When asking in the jscodeshift repo, they said to investigate the printer here in `recast`.

Relevant workspace: http://astexplorer.net/#/5j2WGLMyTF/1

**Comment by benjamn** [comment]
Is this a syntax bug or just a preference against semicolons?

**Comment by benjamn** [comment]
For some background, pretty-printer configurability is an ongoing project (see https://github.com/benjamn/recast/issues/226), but if we can agree there is one right way to do this, then it should be pretty easy to make the printer work that way.

**Comment by joshblack** [comment]
I don't believe it's a syntax bug. It's definitely a style preference for the codebase I'm trying to codemod older stuff to. If the standard for property initializers is to have a semicolon though, I'm all for it and won't have a need for this!

**Comment by zertosh** [comment]
FWIW, the semicolon is required to help mitigate unbounded-lookahead issues:

```js
class Foo {
  static foo = {
    bar: 'baz'
  }
  [qux]() {}
}
```

**Comment by joshblack** [comment]
Oh wow, didn't know that. Thanks for the heads up!
