### ISSUE TITLE
Problems with output when modifying decorators

### ISSUE THREAD

**Issue by kumarharsh** [benjamn/recast#241]
[Migrated from https://github.com/facebook/jscodeshift/issues/82#issuecomment-167108123] 

Say I have this code:

```js
@Radium
export default class Button extends React.Component {
  render() {}
}
```

Now, when I'm trying to add another decorator the to list, like so:

```js
return j(file.source)
  .find(j.ExportDefaultDeclaration)
  .filter(p => (decl = p.value.declaration).type === 'ClassDeclaration'
       && decl.superClass.object.name === 'React' && decl.superClass.property.name === 'Component')
  .replaceWith(p => {
      const classDecl = p.value.declaration;
      classDecl.decorators.push(j.decorator(j.identifier('injectStyle')))
      return p.node;
  })
  .toSource();
```

the output code is being mangled, and the decorators are inserted AFTER the `export default` bit. Also, the original decorator is still maintained...

```js
@Radium
export default @Radium
@injectStyle
class Button extends React.Component {
  render() {}
}
```

**Comment by kumarharsh** [comment]
Also, I've got it working with this `replaceWith` function:

```js
replaceWith(p => {
  p.value.declaration.decorators.unshift($injectStyle)
  return j.template.statement`${p.node}`;  // this outputs correctly
})
```

**Comment by benjamn** [comment]
Are you sure the decorator is allowed to appear before the export token? If so, this is a rare example of code belonging to a child node (the class declaration) but not printing inside the bounds of the parent node (the export declaration). If that's really how it has to work, then we can address that oddity, but it would be a regrettable violation of an invariant that holds for everything else. Also, decorators aren't finalized yet (still stage 1, I believe), so this would be something to bring up with tc39.

**Comment by kumarharsh** [comment]
@benjamn yes, it was a little odd, but I did check it. The decorators indeed reside within the `ClassDeclaration` tree, even in this scenario:

```js
@decorator2
@decorator1
export default class X {
 ...
}
```

**Comment by benjamn** [comment]
Ok, thanks for confirming. I can definitely handle this with some special cases:
- the pretty-printer case for export declarations will need to be responsible for printing any decorators attached to the child declaration
- decorators should not be printed when the parent node is an export declaration
- when reprinting the AST, a change in the decorators of a node should trigger the fallback pretty-printer all the way up to the parent export declaration, if any

**Comment by kumarharsh** [comment]
There's another problem:

when I add a new decorator the the class, the old decorators are written twice (or rather, the old decorators are NOT removed from the source, and the whole list of decorators is again added)

http://astexplorer.net/#/wa58xvW12J

**Comment by benjamn** [comment]
I believe this is due to faulty `.loc` information for classes with decorators. Specifically, the `.loc.start` and `.loc.end` positions for the `ClassDeclaration` only include the class itself, even though the decorators "belong" (as a child property) to the class node. I've solved this kind of problem using the [`getTrueLoc` utility function](https://github.com/benjamn/recast/blob/b0f031b1a36199308a1eb77cc9709d554f14e671/lib/util.js#L86) in the past.

Added another bullet to the [list of action items above](https://github.com/benjamn/recast/issues/241#issuecomment-167340975):
- decorators should be contained in the [`.loc.start`, `.loc.end`) range of the node responsible for printing them

**Comment by benjamn** [comment]
@kumarharsh if you have the time to submit a pull request with failing test cases, I would gladly merge them when I fix this!

**Comment by benjamn** [comment]
More tests would still be welcome, even though I believe this is now fixed.

**Comment by benjamn** [comment]
Really fixed by https://github.com/benjamn/recast/commit/c17c292a2deb6d7a825ed95b2264a81971661769.

**Comment by deoxxa** [comment]
I think this might not be fixed. Or might be broken again. Take a look at [this thing here on astexplorer](https://astexplorer.net/#/u3VVq5Rew1/1). This is running via jscodeshift.

Input code:

```js
import React, { Component, PropTypes } from 'react';
import { pure } from 'recompose';

@pure // look where this ends up
export default class X extends React.Component {
  static propTypes = {a: PropTypes.string};
}
```

Transform:

```js
export default function(file, api) {
  const j = api.jscodeshift;
  
  return j(file.source).find(j.Program).forEach((p) => {
    p.value.body.unshift(j.importDeclaration([], j.literal('x')));
  }).toSource();
}
```

Output:

```js
import "x";
import React, { Component, PropTypes } from 'react';
import { pure } from 'recompose'; // look where this ends up
export default class X extends React.Component {
  static propTypes = {a: PropTypes.string};
}
```
