### ISSUE TITLE
Modifying parent is eating decorators

### ISSUE THREAD

**Issue by kumarharsh** [benjamn/recast#243]
If I modify any line, and do a `p.parent.insertBefore(...)` or `insertAfter()`, then any decorator on any class anywhere in the file is removed (not rendered) in the final output.

**Comment by kumarharsh** [comment]
Infact, using a simple `[].splice` also has the same effect.

**Comment by kumarharsh** [comment]
Reproducible example: http://astexplorer.net/#/dYBDJcHGVu

**Comment by benjamn** [comment]
Commented on the other issue: https://github.com/benjamn/recast/issues/241#issuecomment-169381963

Closing this issue because the other issue seems more general.

**Comment by fkling** [comment]
I updated astexplorer to v0.10.41, but the problem mentioned here still exists.
