### ISSUE TITLE
Trailing block comments printed before node?

### ISSUE THREAD

**Issue by dgreensp** [benjamn/recast#257]
This leads to diffs like this one, which move `/*eslint*/` comments around:

```
     /*eslint-disable no-unused-expressions*/
     // Force layout by accessing height, needed in order to CSS animations to
     // take effect
-    wrapperNode.offsetHeight;
     /*eslint-enable no-unused-expressions*/
+    wrapperNode.offsetHeight;
```

The relevant code appears to be here: https://github.com/benjamn/recast/blob/9b32ded58db4538b644d59a156a0a95959b147a1/lib/comments.js#L348

It looks like trailing comments are (intentionally?) printed before their node rather than after, even for block comments, which narrowly avoid being converted to leading comments a few lines earlier.  I'd love to submit a PR for this.  What is the rationale of how it's currently written?  Thanks!

**Comment by dgreensp** [comment]
Oh, I totally misread that code; `printComments` is actually supposed to print the path itself in the middle.  I'll look again at what's happening.

**Comment by benjamn** [comment]
Here's a previous discussion of this behavior: https://github.com/benjamn/recast/issues/191

Feel free to work on a PR, just please be aware that this behavior is an intentional compromise.

**Comment by dgreensp** [comment]
In that issue, though, block comments don't move.

**Comment by dgreensp** [comment]
It's caused by a typo; `"Block"` should be `"CommentBlock"`.  Shall I prepare a PR?

**Comment by benjamn** [comment]
Oh, that's a difference between the Babel and Esprima ASTs, not exactly a typo. Please do prepare a PR to include `CommentBlock` (and `CommentLine` if necessary), but let's make the logic tolerant of either variation, so that Recast can avoid enforcing an opinion about which parser you should use.
