### ISSUE TITLE
typeParameters on DeclareClass node are not printed

### ISSUE THREAD

**Issue by kyldvs** [benjamn/recast#266]
See: http://astexplorer.net/#/gyg5PMM6KT

(there are also issues involved with constructing DeclareClass nodes via j.declareClass, but that issue isn't blocking me right now)

**Comment by kyldvs** [comment]
@jeffmo @gabelevi

**Comment by kyldvs** [comment]
I guess declare class in general prints very poorly, it was unusable for my needs so I switched to class syntax and fixed it up with some regexes at the end :/

**Comment by valerybugakov** [comment]
Bumped into the same issue. Is there a workaround?

**Comment by valerybugakov** [comment]
Ok, it seems that my case with `CallExpression` `typeParameters` is fixed in this PR: https://github.com/benjamn/recast/pull/613. This update is just not yet published by `jscodeshift`.

**Comment by eventualbuddha** [comment]
Looks like `jscodeshift`’s dependency on recast is `^0.18.1`, which should pull in `0.18.5` unless I’m missing something. Try re-installing it?
