### ISSUE TITLE
Regression in JSX printing

### ISSUE THREAD

**Issue by cpojer** [benjamn/recast#267]
Repro: check out https://github.com/cpojer/js-codemod and run `npm test touchable` – the JSX output isn't properly indented.

Doesn't happen in 0.11.2 but happens in 0.11.3.

A wild guess is that this is related: It is probably: https://github.com/benjamn/recast/commit/8abe4c443f2555542d6aa82385dbe74f80beab5d

**Comment by benjamn** [comment]
I'll get to this as soon as I can!

**Comment by benjamn** [comment]
@cpojer If I revert this, will it break your tests again, or did you just disable the test?

**Comment by cpojer** [comment]
Nah it should finally fix the failing test :D

**Comment by benjamn** [comment]
I believe this was fixed (long ago) by https://github.com/benjamn/recast/pull/305.
