### ISSUE TITLE
Updating location information after node modification.

### ISSUE THREAD

**Issue by Mindonaut** [benjamn/recast#276]
After modifying AST, i.e. for code instrumentation, the location information is no longer valid.

Is there a method that updates the location information of a node, after it has been updated? Is this something that others would find useful?

**Comment by tivac** [comment]
Yes, I've been struggling with this as well.

**Comment by benjamn** [comment]
The original `.loc` information is still perfectly valid in the sense that it identifies the *original* source code for the node, which is vitally important when Recast reprints the AST. It might be possible to obtain the resulting location information after calling `recast.print`, in some way that's more efficient than just re-parsing the code, but I'm definitely not willing to modify the original `.loc` objects.
