### ISSUE TITLE
Dumping and loading AST

### ISSUE THREAD

**Issue by VinceG3** [benjamn/recast#328]
Hi, I was wondering what I could use to load AST after I've dumped it to JSON. I can't just pass loaded JSON to `recast.print` because the loaded objects aren't of the right prototype, so they're missing methods.

Is there a library function or a code snippet I could use?

**Comment by benjamn** [comment]
AST nodes don't have useful prototypes or methods, but they do have [a non-enumerable property called `.original`](https://github.com/benjamn/recast/blob/3a0de50f404cd75db5a8a7c34ff1102270d9de82/lib/parser.js#L114), which is likely to be the source of your problems.

There's also a chance of reference cycles in an AST (especially those produced by Babel/Babylon), which will confuse `JSON.stringify`. If that's the problem, I have another library called [`arson`](http://npmjs.org/package/arson) that can encode arbitrary objects.

**Comment by benjamn** [comment]
Now that I think about it, the `Lines` objects attached to AST nodes as `node.loc.lines` probably are not easily serializable (certainly not by `JSON.stringify`).

Thanks for bringing up this use case. Serialization is definitely worth thinking about. Out of curiosity, why do you need to store the AST as a string? Are you caching parsed ASTs to disk or something?

**Comment by VinceG3** [comment]
Yes, it was the lines it complained about when I tried to parse them back in.

Well, what I want to do is to manipulate the ASTs with Ruby. I'm a Ruby dev, and I find working in Javascript painful. At first I tried using `ast-types`, but after awhile I just wanted Ruby.

I'd use `rkelly-remix` if it handled JSX. A bit of a toss-up right now whether just doing it in Javascript right now would be easier than extending `rkelly-remix` to handle JSX.

https://github.com/nene/rkelly-remix

The nuclear option would be to implement my own JSX parser in Ruby, I may try that out before moving forward with one of the above options. It might be less work than I think if I start small and slowly add features as I need them.

What I'm ultimately trying to do is to implement either an auto-refactoring plug-in for an existing editor, a new editor with refactoring tools built in, or a special refactoring tool that's not an editor.

**Comment by benjamn** [comment]
Serializing `Lines` objects, sending them to Ruby, sending them back to JS, and deserializing them seems costly/difficult, but maybe that's not necessary.

I haven't tested this idea, but you might be able to replace the `.original` reference on every AST node with a unique ID, serialize that simpler structure, manipulate it in Ruby, then send it back to JS, and replace all the the IDs with the original `.original` references. Ruby won't be able to inspect the `.original` information, but at least it will be able to preserve the references.

**Comment by VinceG3** [comment]
Thanks, but I started writing a Javascript parser in the meantime, it seems like the best way forward considering what I want to do.

Thanks anyway!
