### ISSUE TITLE
An option to disable trailing commas in function calls

### ISSUE THREAD

**Issue by mdebbar** [benjamn/recast#335]
Trailing commas in objects, arrays and function calls are separate proposals for ES. Some projects support one but not the other. Right now, Recast supports trailing commas through a single option `trailingComma` for everything. It would be nice to have more granular control over trailing commas: `trailingCommaObjects`, `trailingCommaArrays`, `trailingCommaFunctions`, etc.

**Comment by mdebbar** [comment]
I can take a stab at this, but we would need to agree on the new option names. Here are some proposals:

```javascript
// Proposal 1 - nested options:
const options = {
  trailingComma: {
    objects: true,
    arrays: true,
    functions: false,
  }
};

const options = {
  // Shortcut for marking all categories as `true`.
  trailingComma: true,
};
```

```javascript
// Proposal 2 - separate options:
const options = {
  trailingCommaObjects: true,
  trailingCommaArrays: true,
  trailingCommaFunctions: false,
};
```

I personally like proposal 1 because it looks more elegant (and also backwards compatible). But I'd love to hear what other people think.

**Comment by benjamn** [comment]
I also prefer Proposal 1 (you read my mind!), though I would maybe say `parameters` instead of `functions`. Please do take a stab if you have the time!

**Comment by mdebbar** [comment]
PR #336 is ready and all tests are passing!
