### ISSUE TITLE
Bug: some code transforms aren't reprinted

### ISSUE THREAD

**Issue by mdebbar** [benjamn/recast#356]
I discovered this issue while working on some code transformations using `babylon` as a parser. I narrowed it down to this minimal repro. The issue seems to happen when:

- Using the `babylon` parser, AND
- The code has a leading empty line, AND
- Replacing a statement in the top-level.

Here is a PR that adds a test for the repro: #355

**Comment by mdebbar** [comment]
I tried debugging the issue but I couldn't find anything suspicious in the AST. It's an issue with the printing, but I couldn't dig deeper since I don't understand the whole picture of how the printer works.

**Comment by benjamn** [comment]
Thanks for reporting this! I came up with a fix that solves the problem, though I also think the `Patcher` should complain more loudly when it skips reprinting a node.

**Comment by mdebbar** [comment]
@benjamn thank you for the fix!
