### ISSUE TITLE
Adding a comment to a return expression causes incorrect output

### ISSUE THREAD

**Issue by alangpierce** [benjamn/recast#362]
If I start with this code:

```js
function f() {
  return 3;
}
```

and add a `// foo` comment on the `3` node, recast prints this result:

```js
function f() {
  return //foo
  3;
}
```

This changes the behavior, since the ASI rules cause the function to return `undefined`.

Here's an astexplorer test case:
https://astexplorer.net/#/m2KsWvHL0l

I'm taking a look at this and hoping to be able to come up with a PR, but any thoughts or pointers would be helpful.

**Comment by benjamn** [comment]
What behavior would you expect?

Possible workarounds/solutions:
* make the comment a Block (`/*...*/`) comment
* make the comment a trailing comment (set `comment.leading = false` and `comment.trailing = true` before pushing onto the `.comments` array of the expression node) so that it appears after the 3
* push the comment onto the `.comments` array of the return statement instead of its argument
* modify recast to warn about this kind of bug
* modify recast to transfer the comment automatically to the return statement (not sure this is universally preferable, but worth thinking about)

**Comment by alangpierce** [comment]
Thanks for the quick response! My thought was to have this output:

```js
function f() {
  //foo
  return 3;
}
```

(I would also be fine with a block comment or a trailing comment or anything like that, though.)

One interpretation of that is your last point (transfer the comment to the return node). Another interpretation is making the printer smart enough to understand that putting a line comment between return and its expression is unsafe, so a line comment on a return expression needs to be placed before the `return` (or anything else that doesn't break the code). But I don't know enough about the implementation to know if that's a reasonable way of thinking about things.

For a little more context, I first ran into this in a project I'm working on where a jscodeshift script converts some arrow functions to `function` declarations, including inserting a `return`. This worked in the vast majority of cases, but if the arrow function body had a comment, it would run into this bug and silently change the behavior of the code. In https://github.com/alangpierce/bulk-decaffeinate/pull/85, I fixed the issue by transferring the comments to the `return` node, as you suggested. But now I'm hitting it again for a bug fix I'm writing for the [create-element-to-jsx](https://github.com/reactjs/react-codemod/blob/master/transforms/create-element-to-jsx.js) script.

My impression is that recast should always print out code that parses to the AST that you gave it (although it's probably not a big deal if comments move around), and that adding a comment to a node should never change runtime behavior, but let me know if you think recast has lower-level responsibilities and calling code needs to be more careful in cases like these.

**Comment by alangpierce** [comment]
Here's another possible output that may work better:

```js
function f() {
  return (
    //foo
    3
  );
}
```

It looks like the `ReturnStatement` printer already has a special case for JSX that prints things in that format, so hopefully I can just reuse that if the first line of the expression code is only a comment. Does that seem reasonable?
