### ISSUE TITLE
Extra blank line after import statement with leading comment

### ISSUE THREAD

**Issue by ghost** [benjamn/recast#371]
```
//Core
import React, { Component, PropTypes } from 'react';

import connect from 'react-redux';
```
But should be:

```
//Core
import React, { Component, PropTypes } from 'react';
import connect from 'react-redux';
```

**Comment by jsnmoon** [comment]
For the curious, I've created a [minimal reproduction for this issue](https://astexplorer.net/#/gist/a561df05b00a6c76978c98009f300e17/latest) using JSCodeShift for AST construction.

**Comment by DivineGod** [comment]
see https://github.com/benjamn/recast/issues/405

**Comment by benjamn** [comment]
Closing for the same reason I closed #405: https://github.com/benjamn/recast/issues/405#issuecomment-368252409

There's no way to represent a group of sequential `import` declarations in the AST, so there's no way to attach a single comment to multiple `import` lines.

**Comment by vivek12345** [comment]
For a program like this
```
async function getNormalData() {
  const c = await getData;
}
```
When I try to insert a try catch on top of the await statement and hoist the variable up like the following function:-

```
async function getNormalData() {
  let c;
  try {
    c = await getData;
  } catch (e) {
    console.log(e);
  }
}
```

Recast leaves one line after `let c`;
Something like this:-
```
async function getNormalData() {
  let c;

  try {
    c = await getData;
  } catch (e) {
    console.log(e);
  }
}
```

Can this be regarded as a bug and fixed?

**Comment by ImanMh** [comment]
Finally I was able to fix my issue by adding **reuseWhitespace** to the printer options, This might be a hack and not work for everyone.

```
print(ast, {
    quote: 'double',
    reuseWhitespace: false,
  });
```

**Comment by towry** [comment]
> Finally I was able to fix my issue by adding **reuseWhitespace** to the printer options, This might be a hack and not work for everyone.
> 
> ```
> print(ast, {
>     reuseWhitespace: false,
>   });
> ```

This seems removed all empty lines.
