### ISSUE TITLE
`Maximum call stack size exceeded` on certain babel ASTs

### ISSUE THREAD

**Issue by jenseng** [benjamn/recast#374]
Depending on presets and the code in question, a babel AST can have circular references (e.g. `_shadowedFunctionLiteral` has a `parent`). This can cause problems for recast's TreeCopier, as it does not detect them and it blows the stack.

It's not really even that much of an edge case, just using [ES2015 default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) is enough to trigger it.

## Minimum repro:
* recast@0.11.22
* babel-core@6.23.1
* babel-preset-es2015@6.22.0

```javascript
var transform = require("babel-core").transform
var recast = require("recast")

var source = "function foo(bar = true) { }"

recast.parse(source, {
  parser: {
    parse: function(source) {
      return transform(source, {code: false, presets: ["es2015"]}).ast
    }
  }
})
```

**Result:** `Maximum call stack size exceeded`

It might be nice to have a way to opt out of copying the AST in `parse`, and just return the original. Or maybe just never make a copy at all? ¯\_(ツ)_/¯ ... as of 212e405e4eaa5836cf0b63c43c94dfaf23d98f8d there's no `Parser` object and afaict the AST is just internal to the `parse` function. Skipping the copy could also speed up recast quite a bit.

**Comment by benjamn** [comment]
Copying the AST is essential to finding the changes during `recast.print`, so not copying isn't really an option.

Also, unless we track circular references in `recast.print` as well, not copying the AST won't really solve the problem.

Avoiding traversing properties that start with an underscore should be safe, and would fix the problem for Babel ASTs (I think?).

Keeping track of seen objects would be the best solution logically, though it has a cost.

**Comment by jenseng** [comment]
Awesome, thanks!
