### ISSUE TITLE
Incorrect whitespacing between two nodes with a leading comment

### ISSUE THREAD

**Issue by jsnmoon** [benjamn/recast#405]
Howdy,

I'm running into an issue where an unexpected newline is added between two nodes if the first node has a leading comment. I've been able to reproduce this using VariableDeclarations and ImportDeclarations so far. Could someone point out where/why this might be occurring?

I've written out a small reproducible case below using VariableDeclarations for reference. 

Thanks!

```javascript
// Assumes root directory of recast project
const recast = require("./main.js");
const types = require("./lib/types");
const b = types.builders;
const eol = require("os").EOL;

const firstLet = b.variableDeclaration('let', [
	b.variableDeclarator(b.identifier('abc'), null)
]);
const secondLet = b.variableDeclaration('let', [
	b.variableDeclarator(b.identifier('efg'), null)
]);
firstLet.comments = [
	b.commentLine(' Leading comment here', true, false)
];
const program = b.program([
	firstLet,
	secondLet,
]);

const printed = recast.print(program).code;
```

Expected code:
```javascript
// Leading comment here
let abc;
let efg;
```
Generated code (value of `printed`):
```javascript
// Leading comment here
let abc;

let efg;
```

**Comment by DivineGod** [comment]
Hi, I just had a look at this to see what was going on.

The VariableDeclaration with a leading or trailing comment will be treated as being multiLine when printed which means it'll be padded by newlines as seen in https://github.com/benjamn/recast/blob/d0df645f218d46ff814b25009e51e323ac8924f5/lib/printer.js#L1723

**Comment by benjamn** [comment]
@DivineGod That's correct.

**Comment by benjamn** [comment]
This is working as designed. I would be happy to consider a PR that refines this behavior, but there's currently no bug here to be fixed.
