### ISSUE TITLE
Failed to print flow AST - unprintable type: "TupleTypeAnnotation"

### ISSUE THREAD

**Issue by mitermayer** [benjamn/recast#422]
TupleTypeAnnotation was explicitly made unprintable on (https://github.com/benjamn/recast/pull/173/files#diff-92f0f9f84108717ce81489fddc9e862aR1009) 

The side effect of that is that it makes printing Ast generated from flow incompatible. 

This is a snippet example of how to replicate this:

```javascript
const parser = require('flow-parser');
const recast = require('recast');

recast.print(
  parser.parse(`
function a(): [1, 2] {
  return [1, 2];
}
`)
).code;
```

The above will error as:
```
Error: unprintable type: "TupleTypeAnnotation"
    at genericPrintNoParens
...
```

**Comment by mitermayer** [comment]
Just as a reference, that is how prettier is handling TupleTypeAnnotation - 
https://github.com/prettier/prettier/blob/e378f5e9baf2865b0ed6fef445f29bb3c47c2ccd/src/printer.js#L1907

**Comment by benjamn** [comment]
Any chance you have time to add a printer `case` for that type?

**Comment by mitermayer** [comment]
Hi @benjamn will try to submit a PR for this during the weekend

**Comment by mitermayer** [comment]
This is caused due to using an already parsed flow AST, similar case to issue (https://github.com/benjamn/recast/issues/423) when using the explicit parser this is no longer occurring.

Due to the above will close this issue.
