### ISSUE TITLE
BigInt syntax support (Stage 3)

### ISSUE THREAD

**Issue by rwaldron** [benjamn/recast#439]
https://tc39.github.io/proposal-bigint/

_NumericLiteral_ ::
&nbsp;&nbsp;&nbsp;&nbsp;_DecimalIntegerLiteral_ _BigIntLiteralSuffix_

_BigIntLiteralSuffix_ :: `n`

**Comment by benjamn** [comment]
Thanks @rwaldron! I'm excited about this syntax. I'll add the types to `ast-types` and a printer case to `recast/lib/printer.js`.

**Comment by rwaldron** [comment]
Excellent!

**Comment by benjamn** [comment]
Implemented by b5a52d8e71f96310b4449a4c7c0329109db4f45a, available in `recast@0.12.9`.
