### ISSUE TITLE
unexpected `lib#fast-path.js#` file at npm

### ISSUE THREAD

**Issue by atian25** [benjamn/recast#449]
![image](https://user-images.githubusercontent.com/227713/33063058-4f2291f4-cedc-11e7-8cce-5c7c9a889f44.png)

is there a bug of publish step ?

that block me from publish vscode extension: 

https://github.com/Microsoft/vscode-vsce/issues/217

**Comment by benjamn** [comment]
Thanks for reporting this problem! This should be fixed in `recast@0.13.0`.
