### ISSUE TITLE
master build is broken

### ISSUE THREAD

**Issue by eventualbuddha** [benjamn/recast#479]
I'm not sure why, but something seems to have changed that is making the build fail on a fresh clone:

```
  441 passing (2s)
  1 failing

  1) Reprinting GraphQL-Tools TypeScript files
       data/graphql-tools-src/test/testDirectives.ts:
     SyntaxError: Unexpected token, expected ")" (880:32)
      at _class.raise (/Users/donovan/src/recast/node_modules/babylon/lib/index.js:772:15)
```

This is the same error that is causing #478 to fail.

**Comment by benjamn** [comment]
Should be fixed by https://github.com/apollographql/graphql-tools/commit/634cde8c885bbc923872467380befc8d8fe4988d; thanks for opening this issue @eventualbuddha!
