### ISSUE TITLE
Printer outputs invalid code for default export of IIFE

### ISSUE THREAD

**Issue by robpalme** [benjamn/recast#516]
Constructing an `export default` of an anonymous IIFE causes the printer to output the following invalid JS.

```javascript
export default function() {}();
```

Desired output is:

```javascript
export default (function() {}());
```

**Comment by benjamn** [comment]
Interesting! The way we usually solve parenthesization issues is by adding rules to `FastPath#needsParens`, if you have time to take a look: https://github.com/benjamn/recast/blob/7f7e76805ba898c5f637e5a27e39830a2c7e221e/lib/fast-path.js#L228
