### ISSUE TITLE
Option to omit `loc` field from output

### ISSUE THREAD

**Issue by octogonz** [benjamn/recast#568]
When I save the AST as a json file, it is huge.  Most of the content seems to be the tokens stored in the `loc` fields.  I tried `recast.parse(code, { tokens: false });` but they are still emitted.

Are the `loc` fields required for analysis to work?  If not, is there a way to omit them?

**Comment by benjamn** [comment]
Yes, we do use tokens and `.loc` information quite extensively! For example: https://github.com/benjamn/recast/pull/537

If you're looking for a good way to simplify an object before saving it to disk, consider using the under-appreciated [`replacer` callback of `JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter).

Real talk though: ASTs are really big compared to source code, and sometimes circular. If there's not a good reason to save them to disk, I would recommend not.

**Comment by octogonz** [comment]
Thanks! I was saving them mainly for debugging purposes to visualize the tree that I'm parsing. So I solved it by simply deleting `loc` before saving.
