### ISSUE TITLE
Formatting of await misses parentheses

### ISSUE THREAD

**Issue by skeggse** [benjamn/recast#589]
The following two functions differ, in that one awaits the result of `a()` while one dereferences `b` off of `a`'s return value and then awaits that value.

```js
async function fnA() {
  return await a().b;
}
async function fnB() {
  return (await a()).b;
}
```

The AST for the latter produces the former in `recast`:

```js
const recast = require('recast');
const {builders} = require('ast-types');

console.log(
  recast.print(
    builders.functionDeclaration(
      builders.identifier('fnB'),
      [],
      builders.blockStatement([
        builders.returnStatement(
          builders.memberExpression(
            builders.awaitExpression(builders.callExpression(builders.identifier('a'), [])),
            builders.identifier('b')
          )
        ),
      ])
    )
  ).code
);

// produces

function fnB() {
    return await a().b;
}
```

Moreover, I can't find a workaround for this bug - I'd like to explicitly wrap the `await` expression in parentheses but don't see a way to do so. **EDIT:** I missed the `ParenthesizedExpression` type.

**Comment by kindy** [comment]
seems [escodegen](https://github.com/estools/escodegen) works fine for `await`.

**Comment by benjamn** [comment]
This is definitely a bug, since Recast takes responsibility for inserting parentheses when necessary to preserve AST structure. There are ways to force parentheses, but that's not the recommended way of handling this. The Recast printer should just get it right.

**Comment by skeggse** [comment]
I opened a possible fix for this benjamn/ast-types#349 - does that seem like the right approach?

**Comment by splitice** [comment]
Just hit this bug as well.

The obvious workaround for those who find this is to throw a function around the await as function calls are correctly handled with awaits.

**Comment by jedwards1211** [comment]
I'm seeing a similar issue when [wrapping a `ConditionalExpression` in an `AwaitExpression`](https://astexplorer.net/#/gist/2e1abb8de248f413b0544e98db4f9d8b/facf95ba969c19f9ecb3b033d4b03abf90b485b9).

**Comment by conartist6** [comment]
I've published a PR which should fix these and other issues with parens and also expands relevant test coverage.

@skeggse I believe it improves on your PR by eliminating parens in places where they are irrelevant, e.g. `new Clazz(await args)`, which would otherwise print as `new Clazz((await args))`.
