### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by DanielRuf** [benjamn/recast#648]
You might want to try GitHub Actions which is more flexible and faster.

Did you already signup to the GitHub Actions beta?

**Comment by eventualbuddha** [comment]
> You might want to try GitHub Actions which is more flexible and faster.

More flexible and faster than what?

**Comment by DanielRuf** [comment]
Than Travis CI. GHA supports 20 parallel jobs for OSS projects, much better srarting times, and much more.

**Comment by DanielRuf** [comment]
Than Travis CI. GHA supports 20 parallel jobs for OSS projects, much better starting times, and much more.

**Comment by eventualbuddha** [comment]
I tried it on one of my projects. The lack of caching support made it a non-starter to move from CircleCI.

**Comment by DanielRuf** [comment]
But this project uses Travis CI ;-)
But in general this should be a blocker.
Also the current CI setup does not use the cache afaik.

https://github.community/t5/GitHub-Actions/Caching-files-between-GitHub-Action-executions/m-p/30974#M630

**Comment by DanielRuf** [comment]
But this project uses Travis CI ;-)
But in general this should be a blocker.

https://github.community/t5/GitHub-Actions/Caching-files-between-GitHub-Action-executions/m-p/30974#M630

**Comment by DanielRuf** [comment]
But let me try a GHA setup of this project and let's see the difference.

**Comment by eventualbuddha** [comment]
It’s not really up to me, anyway. @benjamn would have to make the call for this project. While I plan to investigate Actions again when they add caching support, that doesn’t mean much for this project.

**Comment by DanielRuf** [comment]
So in general it would make more sense to move this repo to an org?
Because it seems only one person can do the needed changes.

**Comment by DanielRuf** [comment]
Personally I would keep the issue open until @benjamn can clarify this.
