### ISSUE TITLE
What constitutes a change to the AST? 

### ISSUE THREAD

**Issue by outofcuriousity** [benjamn/recast#668]
Trying to build an obfuscator-type program that will change values within the ast. However, I have been so far unable to figure out how to do this? 
Simply iterating through ast.tokens and changing values does not output those changes within the printed AST. I am trying to do this in an away that allows me to iterate through all token values within a code base to change them, (not just identifiers or function names). 
I suspect I am doing something wrong as I am unfamiliar with the APIs here.

```
const code = [
    "a = 'hello';"
].join("\n");

const ast = polycast.parse(code);
ast.tokens[0].value = "foobar";

const output = polycast.print(ast).code;
```

**Comment by eventualbuddha** [comment]
Tokens are just for reference. Recast (and others) do not reconstruct JavaScript from an AST by looking at just the tokens. In general you should not change the tokens at all. Just think of them as immutable and referencing the original source code.

Check out astexplorer.net for an example of how to manipulate an AST. Also, this part of the [Babel Plugin Handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#toc-transformation-operations) may be useful to you.

Also, if your goal is to obfuscate JavaScript source code, you may not even need recast unless you actually want to preserve comments and formatting. In that case you can just use `@babel/core` directly.
