### ISSUE TITLE
Proposal: Allow transforms to be loaded from npm modules

### ISSUE THREAD

**Issue by pdubroy** [benjamn/recast#68]
It would be cool if transforms could be easily loaded from NPM modules. People could publish small transforms (e.g. recast-arrow-functions), kind of like Grunt tasks.

A strawman proposal is here: a9155d6850f4c29e000ab0b4b477b90f688edabb. This only allows a single transform to be specified, but I could imagine supporting something like: `recast --tranforms recast-arrow-functions,recast-foo,./lib/mytransform.js sourceFile.js`.

What do you think?

**Comment by benjamn** [comment]
I realize this is a very old issue, but I believe [`jscodeshift`](https://github.com/facebook/jscodeshift/) now achieves the spirit of this request!
