### ISSUE TITLE
Recast generates incorrect range and loc information for source code containing tabs

### ISSUE THREAD

**Issue by mrquantos** [benjamn/recast#683]
Hi,

Thank you @benjamn and all contributors for creating awesome recast.

I am using `jscodeshift`, which delegates to `recast`, to search a code base for specific code patterns and generate output containing file paths with line and column number where that code pattern appears. It depends on `range` and `loc` information in generated AST. 

I have found out that `recast` generates incorrect `range` and `loc` information when source code contains tabs, the bug appears to be in recast itself as I have tried it with different parsers. 

The bug is reproduce able (with/without any configurations) with following code containing tab at start position.
```
	var foo;
```
For comparison with other parsers I have saved two snippets with above code on [astexplorer.net](https://astexplorer.net) 
The first one has 'recast' selected as parser [here](https://astexplorer.net/#/gist/4e5b56526362172b535e360125de2bbb/7278f96b1a0979b98a3181947806d6290fd2aee6)
And the second one has 'esprima' selected as parser [here](https://astexplorer.net/#/gist/6cc8334aea552752645fc836b7c42aa3/34c3f3ae5ab4d17239c7ff260d142509e2e989f4)

If we compare ASTs generated by `recast` and `esprima`, in the AST generated by `esprima`, the `range` for `VariableDeclaration` starts from 1 while it starts from 4 in AST generated by `recast` and the same is true for `start.column` number in `loc`.

I suspect, this is due to the reason that `recast` converts all tabs to spaces before passing source code to parser in `parser.ts` [here](https://github.com/benjamn/recast/blob/278f899d85c0f2e84c0e170ea4d598495373a508/lib/parser.ts#L17) and [here](https://github.com/benjamn/recast/blob/278f899d85c0f2e84c0e170ea4d598495373a508/lib/parser.ts#L24)

Is this intended or a bug?

Please review, thank you!

**Comment by eventualbuddha** [comment]
I can’t speak to whether this was intended, but it does seem to be integral to the way it works. I’m definitely in favor of having correct location information, but I do wonder what you’re doing that requires it.

**Comment by benjamn** [comment]
Not a bug! The `range` and `loc` information is perfectly correct, though it's derived from the source code with tabs replaced by spaces. If the `loc` information was incorrect, everything Recast does would be a shambles.

Recast converts tabs to spaces so all its internal logic can work in terms of spaces. Tabs might be fine for writing source code by hand, but they're kind of a nightmare to deal with in a programmatic fashion, if you care about correct (re)indentation of code, because the visible width of a tab depends on its starting column.

Recast is able to preserve tabs in existing code, and generate new code that uses tabs whenever possible, so it's still (intended to be) a fine tool for processing code that uses tabs.

**Comment by mrquantos** [comment]
@eventualbuddha @benjamn thank you for your reply!

@benjamn great, its good to know that its not a bug.
Following may not be a bug as well but let me just report for completeness.
```
export default foo;
```
`foo` `Identifier` `loc` gets a value of null, it can be viewed [here](https://astexplorer.net/#/gist/8461ed7f7f46150d004dff632bf5f108/cd8a620a4cd2faede1b456b522ecac8c284e80b4), although null is valid value according to Mozilla Parser API but I wanted to report just in case.




@eventualbuddha 

> but I do wonder what you’re doing that requires it.

Following is a little bit of context in which I am trying to use `recast`, you may skip it.

I am trying to make sense of a large code base, and I wanted to make a graph of its complete component inheritance hierarchy, I am not aware of any tool that does that, so I am trying to make one, it is just an experiment and I am not sure if it would work.

The code base is using class `extends` and custom `foo.extend()` to extend existing components. It contains ES6 `import` and `export` and CommonJS `require` and `module.exports` to import and export components respectively. 

The code base does not follow one component per module convention strictly, it may be defining a component `foo` in a module and exporting a function `bar` which uses that component, any other component extending from `bar` function is not a child of `foo`, so module dependency graph generator tools like `madge` would not be a good fit for this because 
- One file/module may not contain exactly one component
- One file/module may define a component but export a function which uses that component

To help making above mentioned tool and to get an idea of different kind of patterns that the code base has, I am writing a script which gets a filter as input, searches all nodes in each file in code base and if any node matches that filter, it recursively gathers node types of 5 of its parents ( configurable ) and generates JSON output with file paths, line and column number in this format `path:line:column`. When I open that JSON output in my editor, I can directly jump to that location where that specific pattern appeared. This is where I noticed that `recast` `range` and `loc` information is different, with tabs in source code, in comparison with my editor because my editor (VS Code) was not jumping to correct location, my editor increases column number by 1 for each tab where as recast increases column number by the amount of `tabWidth` ( I am not sure ).

**Comment by eventualbuddha** [comment]
I see. Thanks for the clarification. If I were building such a tool I would use a wrapper around `@babel/parser` I wrote called `@codemod/parser` that just configures Babel to be as lenient as possible in what it parses. You can of course just use `@babel/parser` directly. Doing so for this task is better than using recast because you’re not planning to use the AST editing features of recast, so you have no reason to incur the performance penalty inherent in using recast. It will also give you more accurate location information.

**Comment by eventualbuddha** [comment]
Also, I once maté such a tool when I worked at Square to run on a large Ember application written in CoffeeScript+CommonJS that was being converted to ES6. I never open-sourced it because it was pretty specific to our setup, but such a thing is both desirable and possible.

**Comment by mrquantos** [comment]
Thank you for recommendations and making `@codemod/parser`, I will definitely check `@codemod/parser`.

>Also, I once made such a tool when I worked at Square to run on a large Ember application written in CoffeeScript+CommonJS that was being converted to ES6. I never open-sourced it because it was pretty specific to our setup, but such a thing is both desirable and possible.

Its good to hear that. If I could make this tool more generalized, I would open-source it. 

Thank you!
