### ISSUE TITLE
Error connecting recast

### ISSUE THREAD

**Issue by OlegBas1996** [benjamn/recast#697]
I try to run a test case and get an error connecting recast
SyntaxError: cannot use import statement outside a module

`import * as recast from "recast";

// Let's turn this function declaration into a variable declaration.
const code = [
  "function add(a, b) {",
  "  return a +",
  "    // Weird formatting, huh?",
  "    b;",
  "}"
].join("\n");

// Parse the code using an interface similar to require("esprima").parse.
const ast = `recast.parse(code);``

How to fix this error?

**Comment by eventualbuddha** [comment]
This is most likely unrelated to recast: https://stackoverflow.com/questions/58211880/uncaught-syntaxerror-cannot-use-import-statement-outside-a-module-when-import

Try `const recast = require("recast");` instead of the import.
