### ISSUE TITLE
new Foo becomes new Foo()

### ISSUE THREAD

**Issue by conartist6** [benjamn/recast#714]

**Comment by eventualbuddha** [comment]
How does this happen? [This very simple example](https://astexplorer.net/#/gist/3fcb5c89a72b2ad1af3a367ae1c37dea/76f0254982be5973ba923ad3b54ee80dec3560b2) does not exhibit this behavior.

**Comment by conartist6** [comment]
Closing for now as I don't even remember what I was seeing anymore.
