### ISSUE TITLE
sourceMapName question

### ISSUE THREAD

**Issue by jeffjo** [benjamn/recast#76]
When I run the following code:

``` javascript
var recast = require('recast'),
    fs = require('fs');

var source = fs.readFileSync('index.js');

var result = recast.print(recast.parse(source, {
  sourceFileName: "index.js"
}), {
  sourceMapName: "map.json"
});

console.log(result.code); // Resulting string of code.
console.log(result.map); // JSON source map.
/*
results.map is:
{ version: 3,
  file: 'map.json',
  sources: [ 'index.js' ],
  names: [],
...rest of output elided...
*/

```

`result.map` contains a `file` property equal to "map.json". Maybe I'm missing something in the [spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#), but I thought this property was supposed to be the name of the generated output file that the source map is associated with, _not_ the name of the map file itself. Furthermore, should the name of the map file ever be used in the generation of the map contents?

Also, I notice in `result.code` that the source map annotation (ie `//# sourceMappingURL=<url>`) is not provided. Are clients of recast responsible for printing this to the final output?

**Comment by thetalecrafter** [comment]
I also ran into this problem in [format-message-loader](https://github.com/thetalecrafter/format-message-loader). The name and example suggest it is what would be the filename of the `.map` file, but it must be the name of the source file to be properly used by downstream source map consumers.
