### ISSUE TITLE
Cannot parse a TypeScript class with a private field?

### ISSUE THREAD

**Issue by thejohnfreeman** [benjamn/recast#879]
I get an "Unexpected token" error at the name of the private field in this simple example:

```typescript
export default class Foo {
  private bar
}
```

Here's a demonstration: https://runkit.com/thejohnfreeman/recast What am I doing wrong? (Please short circuit this issue if the project, or even just the TypeScript portion, is not under active development. Just let me know.)

**Comment by thorn0** [comment]
see #884

**Comment by thejohnfreeman** [comment]
Importing `@babel/parser` instead of `babylon` fixed it, as @thorn0 suggested. Thank you!
