### ISSUE TITLE
Typescript type casting breaks parsing

### ISSUE THREAD

**Issue by kachurun** [benjamn/recast#947]
I am using [Riot.js](https://github.com/riot/riot) for development and noticed that using typecasting in TS syntax breaks compilation of components.

@gianlucaguarini suggested that this is a problem from Recast and provided this example:

`AS` syntax:
https://runkit.com/gianlucaguarini/60cc3c42e8ef72001a79b4c3

`<>` syntax:
https://runkit.com/kachurun/60d2f2bdedc34e001ad42bee

Related riot bug: https://github.com/riot/riot/issues/2926

**Comment by eventualbuddha** [comment]
Your example doesn’t tell recast or Babel to use TypeScript parsing. Perhaps you’re missing a configuration option?

**Comment by GianlucaGuarini** [comment]
@eventualbuddha the babel parser supports typescript already https://runkit.com/gianlucaguarini/60d353e7ba9d31001ae3fd74

The issue seems to come from `recast`. Switching to the `typescrpt` parser doesn't solve the issue

**Comment by kachurun** [comment]
I don't see any option explicitly indicating the need to use TS in either `recast` (https://github.com/benjamn/recast/blob/master/lib/options.ts) or `@babel/parser` (which supports TS by default: https://babeljs.io/docs/en/babel-parser#options)

I also try to enable https://babeljs.io/docs/en/babel-plugin-transform-typescript for babel and it not have affect: https://runkit.com/kachurun/60d353e3a6c6ff001ac5eb7e

**Comment by bnjmnt4n** [comment]
Please read https://github.com/benjamn/recast#using-a-different-parser

**Comment by eventualbuddha** [comment]
`babylon` is what the Babel parser was called originally, but it hasn't been updated in 3 years. It moved to `@babel/parser` as others have indicated. If switching to `@babel/parser` with the appropriate options or using recast's typescript parser don't work for some reason, comment here and we can look into it more.

**Comment by kachurun** [comment]
@eventualbuddha I replace babylon with babel/parser in this example:
https://runkit.com/kachurun/60d355c08c6906001aacf201
and it still breaks on `@babel/parser/lib/index.js`
Now I cannot be sure that the problem has something to do with recast. I think it babel/parser bug.

**Comment by eventualbuddha** [comment]
@kachurun you're using the wrong parser in that example. You want `recast/parsers/typescript`: https://runkit.com/eventualbuddha/60d360f18c6906001aacf96d

**Comment by kachurun** [comment]
> ~Please read https://github.com/benjamn/recast#using-a-different-parser~
> 
> Actually, I've realized that the readme recommended installing `babylon`, which appears not to have the same configuration syntax, and hence the TypeScript parser does not work. The following using `@babel/parser` does however: https://runkit.com/60d35a1ba6c6ff001ac5efa9/60d35a2ab416ee001ab72d9e.

Omg, it works, thank you!
