### ISSUE TITLE
Get NodePath from Node or Location

### ISSUE THREAD

**Issue by leumasme** [benjamn/recast#955]
I am getting searching nodes in the AST via a third-party library.
Let's just say Identifier nodes.
I now want to replace these nodes with recast.
The way i know is NodePath.replace
This however does not work, as my Identifier is not a NodePath.
How would i turn my Identifier into a NodePath<Identifier> to modify it?
Is there a better way to do this?
Is there a general way of getting a NodePath from node.loc data?

**Comment by eventualbuddha** [comment]
You can modify the AST however you want. You don't need a `NodePath`, though that is a convenient way to do it. So if you have an `Identifier` node you can just modify it. For example, you can set its `name` property. Or, if you have its parent, you can replace it just by setting the appropriate property on the parent. For example, to change the `foo` to `foo.bar` in `foo()` if you have the `CallExpression` as `parent`, then you'd just set `parent.callee = b.memberExpression(node, b.identifier('bar'))`.
