### ISSUE TITLE
Replacing ImportDeclaration leads to 'does not match type string'

### ISSUE THREAD

**Issue by sziberov** [benjamn/recast#980]
I believe this is not something that should happen?

![Screenshot_1310](https://user-images.githubusercontent.com/7362968/128983773-12bd565d-6464-4d76-bcb0-18e6f51a9085.png)

**Comment by tupe12334** [comment]
Can you elaborate more about want you expect to happen and what is your goal?

**Comment by sziberov** [comment]
@tupe12334 It's almost year passed by, my goal changed dramatically since then. But what's about this issue, is that I wanted to replace ImportDeclaration with CallExpression, although as shown at scheenshot, .replace() did not work at all with this node type.

**Comment by eventualbuddha** [comment]
I believe this is an issue with astexplorer.net, not with recast. I ran this in my dev workspace for recast and it worked just fine:

```ts
> require('./').types.builders.stringLiteral('a')
{
  value: 'a',
  loc: null,
  type: 'StringLiteral',
  comments: null,
  extra: { rawValue: 'a', raw: '"a"' }
}
```

**Comment by sziberov** [comment]
@eventualbuddha Creating strings has nothing to do with this, it's fine and I used it just for testing purpose.

**Comment by eventualbuddha** [comment]
If you have an example that uses recast that fails I'd be happy to look at it.
