### ISSUE TITLE
Typescript 4.4.2 breaks recast

### ISSUE THREAD

**Issue by SnarkBoojum** [benjamn/recast#983]
Trying to package the new recast 0.20.5 for Debian, I'm stuck because its code isn't compatible with the latest typescript we have.

**Comment by eventualbuddha** [comment]
Does it work if you add `"skipLibCheck": true` to your `compilerOptions`?

**Comment by SnarkBoojum** [comment]
Sorry it took so long to answer you ; the error must have been transient, because now everything is fine.

Thanks!
