### ISSUE TITLE
Recast breaks JavaScript 🤯 

### ISSUE THREAD

**Issue by SiddharthShyniben** [benjamn/recast#991]
```js
const {parse, print, types, visit} = require('recast');

function change(JS) {
	const ast = parse(JS);

	visit(ast, {
		visitVariableDeclaration: visitVariable,
	});
}

function visitVariable() {
	let arr = [1, 2, 3, 4];

	arr.forEach(item => {
		console.log('First loop iter');
	});

	arr.forEach(item => {
		console.log('Second loop iter');
	});

	return false;
}

change(`let foo = 1; let bar = foo / 60;`);
```

This logs `First loop iter`, then `Second loop iter` (!), then `First loop iter` (!!), then `Second loop iter` (!!!).

This is a really confusing and dangerous problem. It breaks JavaScript itself. It also happens for `for` loops.

Any workarounds/fixes?

**Comment by eventualbuddha** [comment]
This is expected behavior. You have two variable declarations and so your visitor function is called twice. Recast isn't doing anything unusual here, just calling a function more than once.

**Comment by eventualbuddha** [comment]
Reading again, I see that it should be logging 4 "first", then 4 "second", then the same again. But you're only seeing one of each twice? How are you running this?

**Comment by SiddharthShyniben** [comment]
I'm running this the usual way, like `node file`. Here's a [runkit](https://runkit.com/siddharthshyniben/javascript-broke)

**Comment by SiddharthShyniben** [comment]
I'm so dumb! Thanks @eventualbuddha That solved it.
